server:
  port: 8087

spring:
  application:
    name: eggs

  r2dbc:
    url: r2dbc:postgresql://db.ipelnpeotujejhjfnxjj.supabase.co:5432/postgres
    username: postgres
    password: vallegrande1004

    pool:
      enabled: true
      initial-size: 2
      max-size: 10
      max-idle-time: 30s
      validation-query: SELECT 1
      acquire-retry: 3
      acquire-retry-delay: 5s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/security-prs2
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com